### ISSUE TITLE
你好，适合x-code的那个版本？我6.0.1编译不出来

### ISSUE THREAD

**Issue by sayiwen** [ifLab/WeCenterMobile-iOS#10]

**Comment by Msr-B** [comment]
我现在正使用Xcode 6.3.1（Swift 1.2）进行开发，开发预计在下周完成，还会有一些改动，等初期完成我们会对外公布开源方案。

发自我的 iPhone

**Comment by Msr-B** [comment]
另外请仅使用最新版本，稍旧版本依赖有问题，会出现submodules无法下载的情况。

**Comment by sayiwen** [comment]
好的，谢谢
